[prod]
; TODO: substitua pelo IP ou hostname do seu VPS na Railway
orderhub-prod ansible_host=SEU_IP_AQUI

[prod:vars]
ansible_user=SEU_USUARIO_AQUI
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
